const en = {
  title: 'Photo frames & grids', hint: 'Insert a frame, then choose a cell to fill it. Drop an image on a cell preview to replace its photo.',
  rect: 'Rectangle', roundRect: 'Rounded frame', ellipse: 'Circle', two: 'Two photos', three: 'Three photos', four: 'Four photos', six: 'Six photos', nine: 'Nine photos', hero: 'Hero mosaic',
  fill: 'Choose photo', crop: 'Reposition / crop', clear: 'Clear photo', gutter: 'Gutter (px)', swap: 'Swap with next cell', cell: 'Photo cell', error: 'Could not load this image. Check its format, size and upload settings.', busy: 'Loading photo…', document: 'Use a document image', empty: 'Empty frame',
}
type Labels = { [K in keyof typeof en]: string }
const cs: Labels = { title: 'Fotografické rámečky a mřížky', hint: 'Vložte rámeček a vyberte buňku k vyplnění. Přetažením obrázku na náhled buňky nahradíte fotografii.', rect: 'Obdélník', roundRect: 'Zaoblený rámeček', ellipse: 'Kruh', two: 'Dvě fotografie', three: 'Tři fotografie', four: 'Čtyři fotografie', six: 'Šest fotografií', nine: 'Devět fotografií', hero: 'Mozaika s hlavní fotografií', fill: 'Vybrat fotografii', crop: 'Posunout / oříznout', clear: 'Vymazat fotografii', gutter: 'Mezera (px)', swap: 'Prohodit s další buňkou', cell: 'Buňka fotografie', error: 'Obrázek se nepodařilo načíst. Zkontrolujte formát, velikost a nastavení nahrávání.', busy: 'Načítání fotografie…', document: 'Použít obrázek z dokumentu', empty: 'Prázdný rámeček' }
const sk: Labels = { title: 'Fotografické rámčeky a mriežky', hint: 'Vložte rámček a vyberte bunku na vyplnenie. Pretiahnutím obrázka na náhľad bunky nahradíte fotografiu.', rect: 'Obdĺžnik', roundRect: 'Zaoblený rámček', ellipse: 'Kruh', two: 'Dve fotografie', three: 'Tri fotografie', four: 'Štyri fotografie', six: 'Šesť fotografií', nine: 'Deväť fotografií', hero: 'Mozaika s hlavnou fotografiou', fill: 'Vybrať fotografiu', crop: 'Posunúť / orezať', clear: 'Vymazať fotografiu', gutter: 'Medzera (px)', swap: 'Vymeniť s ďalšou bunkou', cell: 'Bunka fotografie', error: 'Obrázok sa nepodarilo načítať. Skontrolujte formát, veľkosť a nastavenie nahrávania.', busy: 'Načítanie fotografie…', document: 'Použiť obrázok z dokumentu', empty: 'Prázdny rámček' }
const pl: Labels = { title: 'Ramki i siatki zdjęć', hint: 'Wstaw ramkę i wybierz komórkę do wypełnienia. Upuść obraz na podgląd komórki, aby zastąpić zdjęcie.', rect: 'Prostokąt', roundRect: 'Zaokrąglona ramka', ellipse: 'Koło', two: 'Dwa zdjęcia', three: 'Trzy zdjęcia', four: 'Cztery zdjęcia', six: 'Sześć zdjęć', nine: 'Dziewięć zdjęć', hero: 'Mozaika z głównym zdjęciem', fill: 'Wybierz zdjęcie', crop: 'Przesuń / przytnij', clear: 'Usuń zdjęcie', gutter: 'Odstęp (px)', swap: 'Zamień z następną komórką', cell: 'Komórka zdjęcia', error: 'Nie udało się załadować obrazu. Sprawdź format, rozmiar i ustawienia przesyłania.', busy: 'Ładowanie zdjęcia…', document: 'Użyj obrazu z dokumentu', empty: 'Pusta ramka' }
export const photoFrameLabels: Record<string, Labels> = { en, cs, sk, pl }
