import {
  AlignCenterHorizontal,
  AlignCenterVertical,
  AlignEndHorizontal,
  AlignEndVertical,
  AlignStartHorizontal,
  AlignStartVertical,
  AlignVerticalJustifyCenter,
  AlignVerticalJustifyEnd,
  AlignVerticalJustifyStart,
  ArrowLeftRight,
  ArrowRight,
  Baseline,
  BetweenVerticalStart,
  Bold,
  Bookmark,
  Braces,
  BringToFront,
  Camera,
  ChartArea,
  ChartBar,
  ChartColumn,
  ChartLine,
  ChartPie,
  ChartScatter,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleArrowLeft,
  CircleCheck,
  CircleQuestionMark,
  Cloud,
  Code,
  Copy,
  Crop,
  Download,
  Ellipsis,
  Eraser,
  Eye,
  EyeOff,
  FilePlus,
  FlipHorizontal2,
  FlipVertical2,
  FolderUp,
  GitBranch,
  Laugh,
  Globe,
  Grid3x3,
  Group,
  Hand,
  Highlighter,
  Image,
  Info,
  Italic,
  Keyboard,
  LayoutGrid,
  Link,
  List,
  ListIndentDecrease,
  ListIndentIncrease,
  ListOrdered,
  LoaderCircle,
  Lock,
  LockOpen,
  LogOut,
  Maximize,
  Menu,
  MessageSquare,
  Minimize,
  Minus,
  Moon,
  MousePointer2,
  MousePointerClick,
  Move,
  MoveHorizontal,
  MoveVertical,
  Music,
  PaintBucket,
  Paintbrush,
  Palette,
  Pause,
  Pencil,
  PencilLine,
  Pipette,
  Play,
  Plus,
  Power,
  Presentation,
  Quote,
  Radar,
  Radical,
  Redo2,
  RemoveFormatting,
  Repeat,
  RotateCw,
  Search,
  Send,
  SendToBack,
  Shapes,
  Share2,
  Smile,
  Sparkles,
  Spline,
  Square,
  SquareFunction,
  Sticker,
  Strikethrough,
  Sun,
  Table,
  Terminal,
  TextAlignCenter,
  TextAlignEnd,
  TextAlignJustify,
  TextAlignStart,
  Timer,
  Trash2,
  Triangle,
  TriangleAlert,
  Type,
  Underline,
  Undo2,
  UnfoldVertical,
  Ungroup,
  Upload,
  User,
  Users,
  Video,
  Volume1,
  Volume2,
  VolumeX,
  X,
} from 'lucide-react'
import type { LucideIcon, LucideProps } from 'lucide-react'

const ICONS = {
  'align-center': TextAlignCenter,
  'align-center-horizontal': AlignCenterHorizontal,
  'align-center-vertical': AlignCenterVertical,
  'align-end-horizontal': AlignEndHorizontal,
  'align-end-vertical': AlignEndVertical,
  'align-justify': TextAlignJustify,
  'align-left': TextAlignStart,
  'align-right': TextAlignEnd,
  'align-start-horizontal': AlignStartHorizontal,
  'align-start-vertical': AlignStartVertical,
  'align-vertical-justify-center': AlignVerticalJustifyCenter,
  'align-vertical-justify-end': AlignVerticalJustifyEnd,
  'align-vertical-justify-start': AlignVerticalJustifyStart,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'baseline': Baseline,
  'between-vertical-start': BetweenVerticalStart,
  'bold': Bold,
  'bookmark': Bookmark,
  'braces': Braces,
  'bring-to-front': BringToFront,
  'camera': Camera,
  'chart-area': ChartArea,
  'chart-bar': ChartBar,
  'chart-column': ChartColumn,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'chart-scatter': ChartScatter,
  'check': Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'circle': Circle,
  'circle-arrow-left': CircleArrowLeft,
  'circle-check': CircleCheck,
  'circle-help': CircleQuestionMark,
  'cloud': Cloud,
  'code': Code,
  'copy': Copy,
  'crop': Crop,
  'download': Download,
  'ellipsis': Ellipsis,
  'eraser': Eraser,
  'eye': Eye,
  'eye-off': EyeOff,
  'file-plus': FilePlus,
  'flip-horizontal-2': FlipHorizontal2,
  'flip-vertical-2': FlipVertical2,
  'folder-up': FolderUp,
  'function-square': SquareFunction,
  'git-branch': GitBranch,
  'github': GitBranch,
  'globe': Globe,
  'grid-3x3': Grid3x3,
  'group': Group,
  'hand': Hand,
  'highlighter': Highlighter,
  'image': Image,
  'indent': ListIndentIncrease,
  'info': Info,
  'italic': Italic,
  'keyboard': Keyboard,
  'laugh': Laugh,
  'layout-grid': LayoutGrid,
  'link': Link,
  'list': List,
  'list-ordered': ListOrdered,
  'loader-circle': LoaderCircle,
  'lock': Lock,
  'log-out': LogOut,
  'maximize': Maximize,
  'menu': Menu,
  'message-square': MessageSquare,
  'minimize': Minimize,
  'minus': Minus,
  'moon': Moon,
  'mouse-pointer-2': MousePointer2,
  'mouse-pointer-click': MousePointerClick,
  'move': Move,
  'move-horizontal': MoveHorizontal,
  'move-vertical': MoveVertical,
  'music': Music,
  'outdent': ListIndentDecrease,
  'paint-bucket': PaintBucket,
  'paintbrush': Paintbrush,
  'palette': Palette,
  'pause': Pause,
  'pencil': Pencil,
  'pencil-line': PencilLine,
  'pipette': Pipette,
  'play': Play,
  'plus': Plus,
  'power': Power,
  'presentation': Presentation,
  'quote': Quote,
  'radar': Radar,
  'radical': Radical,
  'redo-2': Redo2,
  'remove-formatting': RemoveFormatting,
  'repeat': Repeat,
  'rotate-cw': RotateCw,
  'search': Search,
  'send': Send,
  'send-to-back': SendToBack,
  'shapes': Shapes,
  'share-2': Share2,
  'smile': Smile,
  'sparkles': Sparkles,
  'spline': Spline,
  'square': Square,
  'sticker': Sticker,
  'strikethrough': Strikethrough,
  'sun': Sun,
  'table': Table,
  'terminal': Terminal,
  'timer': Timer,
  'trash-2': Trash2,
  'triangle': Triangle,
  'triangle-alert': TriangleAlert,
  'type': Type,
  'underline': Underline,
  'undo-2': Undo2,
  'unfold-vertical': UnfoldVertical,
  'ungroup': Ungroup,
  'unlock': LockOpen,
  'upload': Upload,
  'user': User,
  'users': Users,
  'video': Video,
  'volume-1': Volume1,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  'x': X,
} as const satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS

export type IconProps = {
  icon: IconName
  className?: string
} & Omit<LucideProps, 'ref' | 'iconNode'>

export function Icon({
  icon,
  className,
  size = '1em',
  strokeWidth = 1.75,
  ...props
}: IconProps) {
  const Cmp = ICONS[icon]
  const classes = ['i-icon', className].filter(Boolean).join(' ')
  return <Cmp className={classes} size={size} strokeWidth={strokeWidth} {...props} />
}

export default Icon
